### ISSUE TITLE
Plot enhancements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#10]
Enhancements for "plots", motivated by using plots in Fourier:

- [x] (1) Add `setData` method
In Fourier, I'd like to statically create 11 `LinePlot` instances that correspond to the 11 harmonics in the Fourier series.  But LinePlot's data set is currently not mutable. Since other components are mutable, and LabelSet goes even further by caching, it certainly seems like LinePlot (and ScatterPlot and BarPlot) should be mutable.

- [x] (2) Restructure BarPlot
BarPlot is not currently structured like LinePlot and ScatterPlot. Factor out an `updateBarPlot` method.

- [x] (3) Override `dispose`
Currently missing and leaks memory, should be similar to other bamboo components

- [ ] (4) Base class
The "plot" classes have several things in common that could be factored out into an abstract `Plot` base class. The commonalities are: `this.chartModel`, `this.data`, `update` method, `setData` method, `dispose` method

- [x] (5) Revise option `valueToColor` in BarPlot.
Currently: `valueToColor: ( x, y ) => 'blue'`
This doesn't make a lot of sense to me, since "value" is one of the elements in `{Vector2} data`.  Better would be:
`vectorToColor: vector => 'blue'`

- [x] (6) Rename `this.nodes` to `this.lines` in BarPlot
They are instances of `Line`, and the update method calls `setLine`.

**Comment by pixelzoom** [comment]
(5) Revise option `valueToColor` in BarPlot.
Currently: `valueToColor: ( x, y ) => 'blue'`
This doesn't make a lot of sense to me, since "value" is one of the elements in `{Vector2} data`.  Better would be:
`vectorToColor: vector => 'blue'`

**Comment by pixelzoom** [comment]
- [ ] (6) Rename `this.nodes` to `this.lines` in BarPlot
They are instances of `Line`, and the update method calls `setLine`.

**Comment by pixelzoom** [comment]
- [ ] (7) Rename "data" to "points"
Partway through the above commits, I realized that "points" was a better name for a collection of `Vector2`.  Rename `this.data` to `this.points`, `setData` to `setPoints`, and  BarPlot `vectorToColor` to `pointToColor`.

**Comment by pixelzoom** [comment]
Oh dear. I just discovered CanvasLinePlot, which for some reason has constructor param `{Vector2[][]} dataSets`, a 2D array. It's also missing `dispose` and not structured like the other "plot" classes.   It also makes me thing that "dataSet" might be a better name than "points" or "data" in the other plot classes.

**Comment by pixelzoom** [comment]
`CanvasLinePlot` is now up to speed with other "plot" classes.  "data" is now "dataSet" throughout.

**Comment by pixelzoom** [comment]
- [ ] (8) For performance, make `this.dataPoints` public.  Client is responsible for calling `update`.
@samreid pointed this out in Slack, to support cases like:

```js
plot.dataSet.push( new Vector2( 0, 2 ) );
plot.update();

plot.dataSet[0].x = 7;
plot.update();
```

It's still useful to have `setDataSet`, and preferable to doing this:

```js
plot.dataSet = dataSet;
plot.update();
```

**Comment by pixelzoom** [comment]
The only enhancement I haven't completed is:

> - [ ] (4) Base class ...

There are 3 problems here:
(1) The plot classes extend different superclasses. This could be resolved using composition and making them all extend Node.
(2) The `update` method is abstract (each subclass has a specific implementation), and `update` is called by the superclass constructor.  I don't see a good way around this.
(3) CanvasLinePlot has a different API, as it deals with 2D `{Vector2[][]} dataSets`. 

Over to @samreid to review the work that's been done, and to brainstorm about the base class issue.

**Comment by samreid** [comment]
I reviewed the existing changes and they look good.  Regarding factoring out a base class for plots, it sounds like we are considering something like this.  This would work for the "path" based plots LinePlot and ScatterPlot: (comments removed for succinctness)

```js
class Plot extends Path {
  constructor( chartModel, dataSet, options ) {
    super( options );
    this.chartModel = chartModel;
    this.dataSet = dataSet;
  }
  setDataSet( dataSet ) {
    this.dataSet = dataSet;
    this.update();
  }
  update() {}
}
```

I don't see a significant advantage in factoring out such a small amount of non-complex code, especially since there is no clear way to do it.  If we were using Java we would probably define a `Plot` interface which has `setDataSet` and `update` methods.

**Comment by pixelzoom** [comment]
Agreed, let's not pursue the base class. Closing.
