### ISSUE TITLE
clippingType bug in GridLineSet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#11]
In GridLineSet.js:

```js
31      clippingType: ClippingType.STRICT
...
41    this.clipped = options.clipped;
...
57    this.chartModel.forEachSpacing( this.axisOrientation, this.spacing, this.origin, this.clippingType, ( modelPosition, viewPosition ) => {

```

Line 41 looks like a bug, and `this.clippingType` is undefined on line 57.  

Should line 41 be this?

```js
41  this.clippingType = options.clippingType;
```

Looking at other bamboo classes....  They have `this.clippingType = options.clippingType`, which is used in their update call when calling `this.chartModel.forEachSpacing`.   Is that what was intended here?

**Comment by pixelzoom** [comment]
Fixed in above commit, @samreid please review.

**Comment by samreid** [comment]
Looks good, thanks for fixing it, closing.
