### ISSUE TITLE
bamboo cleanup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#12]
A bunch of misc things to clean up:

- [x] Several `dispose` methods are documented incorrectly, missing `@overrides`.

- [x] ChartModel leaks memory, needs to implement `dispose` and handle `this.transformChangedEmitter`.

- [x] AxisNode leaks memory, needs to override `dispose`.

- [x] ChartRectangle leaks memory, needs to override `dispose`.

- [x] LabelSet and SpanNode set `this.children` without verifying `!options.children`.

- [x] Missing visibility annotations for misc fields.

- [x] GridLineSet, LabelSet, SpanNode, and TickMarkSet probably don't need to call `mutate` and can pass options to `super`.

**Comment by pixelzoom** [comment]
Done, @samreid please review.

**Comment by samreid** [comment]
I reviewed the changes and didn't have any recommendations, thanks!  Closing.
