### ISSUE TITLE
TODO: LabelSet extent

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#13]
Address this TODO in LabelSet.js:

```js
      // TODO https://github.com/phetsims/bamboo/issues/13 This seems critical to get right, if it is shared by
      //   TickMarkNode.  Also, is it odd to put this to 0 (or a small number) when you don't have ticks?
      extent: 10,
```

I'll start by assigning to @samreid. Happy to discuss, but I'm not quite sure what's going on here.

**Comment by samreid** [comment]
I factored out the constant and used it in the label set and tick mark set.  @pixelzoom does this seem good to you?

**Comment by pixelzoom** [comment]
I'm OK with leaving this as is.   But...

I would not have named this `DEFAULT_LABEL_EXTENT`, since it's tick marks (not labels) that have extent, and the tick mark extent determines where the label should be placed.  And rather than put this in BambooConstants.js, I would have created static constant `TickMarkSet.DEFAULT_EXTENT`, and used that value in LabelSet.

If you do leave it as is, I'd recommend at least renaming it to `DEFAULT_TICK_MARK_EXTENT`, and documenting it.

**Comment by samreid** [comment]
Sounds good, I moved the constant to `TickMarkSet.DEFAULT_EXTENT`, ready for re-review.

**Comment by pixelzoom** [comment]
Looks good.  

One nit in the above commit.  Documenting as "static" is a bit redundant, and I haven't been doing so for static constants (for the same reason as `static` methods).  But `@static` is preferrable to "static".

Closing.
