### ISSUE TITLE
improve CanvasLinePlot API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#16]
CanvasLinePlot is a high-performance way of drawing multiple plots using CanvasNode.   Some issues with the API:

(1) The name is CanvasLinePlot (singular), when it's capable of drawing multiple plots. Rename to CanvasLinePlots (plural)?

(2) The style (stroke, lineWidth,...) of the plots is hardcoded, and all of the plots are rendered in the same style. The API needs a way to describe the style _per plot_. For example, Fourier uses a different stroke for each plot.

(3) Plot styles need to be mutable.  For example, Fourier changes the plot strokes to grayscale when you pointer-over one of the amplitude sliders.

(4) The current hardcoded lineWidth is `0.1`.  That appears to be specific to DemoCanvasLinePlot, and is unlikely to be appropriate elsewhere.

Assigning to @samreid to discuss what needs to be included for "plot style".  Definitely stroke and lineWidth.

I'll be using this in Fourier immediately.

**Comment by pixelzoom** [comment]
How about something like this?

```js
// Default plot style
const DEFAULT_STYLE = {
  stroke: 'black',
  lineWidth: 1
};

  constructor( chartModel, dataSets, options ) {

    options = merge( {

      // {{stroke:ColorDef, lineWidth:number}[]} one per dataSet, unspecified entries are filled in with DEFAULT_STYLE
      styles: []
    }, options );

    assert && assert( options.styles.length <= dataSets.length, 'too many entries in options.styles' );
    for ( let i = 0; i < dataSets.length; i++ ) {
      options.styles[ i ] = merge( {}, DEFAULT_STYLE, options.styles[ i ] || {} );
    }

    // @public if you change this directly, you are responsible for calling update
    this.styles = options.styles;
```

**Comment by samreid** [comment]
I have a more general proposal that will be ready to share shortly.

**Comment by pixelzoom** [comment]
@samreid and I discussed his more general approach on Slack.  Basically a ChartCanvasNode that extends CanvasNode, has the view bounds of the ChartModel, and can draw a set of CanvasPaintables (or whatever they were called :)  that implenment `paintCanvas( context )`.  This approach looks really nice, definitely superior to my above proposal, and @samreid will continue to flesh it out.

**Comment by samreid** [comment]
I committed a first draft of this, @pixelzoom can you please review and test at your convenience?

**Comment by pixelzoom** [comment]
> (1) The name is CanvasLinePlot (singular), when it's capable of drawing multiple plots. Rename to CanvasLinePlots (plural)?

@samreid your thoughts on this?

**Comment by samreid** [comment]
`ChartCanvasLinePlot` renders one data set.  `ChartCanvasNode` renders multiple `CanvasPainter` instances.

**Comment by pixelzoom** [comment]
Got it, thanks for clarifying.

**Comment by pixelzoom** [comment]
@samreid FYI, a few changes in the above commits. 

`ChartCanvasLinePlot` had a broken `dispose` method, looked like a copy-paste from `LinePlot`, so I deleted it.

`ChartCanvasLinePlot` didn't seem like the correct name, so I renamed to `CanvasLinePlot` --- the Canvas version of `LinePlot`. 

`ChartCanvasNode` doesn't strike me as the best name, but I haven't thought of a better one yet.  We want a name that says "responsible for drawing CanvasPainter instances" (assuming CanvasPainter is the best name).

Onward to integrating this into Fourier.

**Comment by pixelzoom** [comment]
One more thing that I changed accidentally (playing around) and reverted...  

`ChartCanvasLinePlot` does not support {ColorDef} for options.stroke.  In Fourier, the line plot colors are Properties, and are update dynamically.

**Comment by pixelzoom** [comment]
Hmm... `ChartCanvasLinePlot` apparent doesn't even support `{Color} stroke`.   So I had to convert my colors to `Color` for PhET-iO, then convert them back to CSS for `ChartCanvasLinePlot`.    

Which parts of `{ColorDef}` should `ChartCanvasLinePlot` support?

**Comment by samreid** [comment]
How about adding `ColorDef.toCSS` for starters?  I'm not sure about listening for changes if it is a property--doesn't seem the responsibility of CanvasLinePlot.

**Comment by pixelzoom** [comment]
I had hoped to use this to improve performance in Fourier, especially while animating in "space & time" domain). But when adjusting amplitudes with sliders (for example) using CanvasLinePlot requires redrawing all of the plots that are managed by the CanvasChartNode. LinePlot allows me to redraw only the plot that is changing.  So I'm not sure that this is going to be a "win".

**Comment by samreid** [comment]
* First of all, calling `paintCanvas` on many curves is much faster than changing a LinePlot path shape and re-rendering it.
* Secondly, in Fourier (at least in Java), in the "space and time" harmonics chart, all curves are moving (not just one).

**Comment by pixelzoom** [comment]
Indeed, it's not an issue when all of the curves are animating, because they all need to be redrawn. I said it's an issue "when adjusting amplitude with a slider", which requires updating 1 plot.   And to be clear, I'm still going down this path, just didn't realize that if any plot changes, I have to redraw all plots.

**Comment by pixelzoom** [comment]
Indeed, it's not a problem when all of the curves are animating, because they all need to be redrawn. I said it's an issue "when adjusting amplitude with a slider", which requires updating 1 plot.   And to be clear, I'm still going down this path, just didn't realize that if any plot changes, I have to redraw all plots.  That's a significant change in the Fourier code, which is currently optimized to draw only the plots that have actually changes.

**Comment by pixelzoom** [comment]
ChartCanvasNode + CanvasLinePlot is much faster than LinePlot in Fourier. 

Fourier always has 11 plots (one for each possible harmonic).  Only the relevant ones should be drawn (based on numberOfHarmonicsProperty) and only if their amplitude is !== 0.

Thoughts on how to change the visibility of CanvasLinePlot specifically, and CanvasPainter generally?  Do I need to change ChartCanvasNode `this.painters` and call `update`?

**Comment by pixelzoom** [comment]
Until CanvasLinePlot stroke supports ColorDef, I've added assertion that it must be {string}.

To address the issue of CanvasLinePlot visibility, I've created subclass HarmonicPlot, which adds `this.visible`, then overrides `paintCanvas` like this:

```js
  paintCanvas( context ) {
    if ( this.visible ) {
      super.paintCanvas( context );
    }
  }
```

**Comment by pixelzoom** [comment]
This is all working nicely in Fourier, with very excellent performance on my MacBook Pro (MacbookPro16,1), iPad 6, and iPhone 11.

Remaining items for this issue:

- [ ] Support for more than `{string} stroke` in CanvasLinePlot
- [ ] Support for visibility in CanvasLinePlot/CanvasPaintable, or leave it up to clients, as I've done in HarmonicPlot?
- [ ] A better name for ChartCanvasNode

**Comment by pixelzoom** [comment]
I'm not sure that I like adding `link`, `unlink`, and `toCSS` to ColorDef for this.   @jonathanolson could you please weigh in?

**Comment by pixelzoom** [comment]
I'm not sure that I like adding `link`, `unlink`, and `toCSS` to ColorDef for this.   @jonathanolson could you please weigh in? 

And there's still the problem of calling ChartCanvasNode `update` when a CanvasLinePlot's stroke Property changes. I don't think that CanvasLinePlot should be responsible for that, but I'd like to hear what the recommended pattern is.

**Comment by jonathanolson** [comment]
This looks like a case where PaintColorProperty could be used (similar to how baseColor is handled in buttons), then just link to that in one place.

**Comment by pixelzoom** [comment]
I think that @jonathanolson is probably referring to the uses of `PaintColorProperty` in sun `ButtonNode`, see relevant definitions below. But I'm having a hard time apply this to `CanvasLinePlot`.

```js
    // @private - Support baseColor being effected by enabled, while still allowing setting the base color.
    this._settableBaseColorProperty = new PaintColorProperty( options.baseColor );

    // @private
    this._disabledColorProperty = new PaintColorProperty( options.disabledColor );
```

**Comment by pixelzoom** [comment]
I think that @jonathanolson is probably referring to the uses of `PaintColorProperty` in sun `ButtonNode`, see relevant definitions below. But I'm having a hard time relating this to `CanvasLinePlot`.

```js
    // @private - Support baseColor being effected by enabled, while still allowing setting the base color.
    this._settableBaseColorProperty = new PaintColorProperty( options.baseColor );

    // @private
    this._disabledColorProperty = new PaintColorProperty( options.disabledColor );
```

I'm also not convinced that we want to introduce PaintDef into `CanvasLinePlot`.  Do we really want to support Gradients and other PaintDefs?

**Comment by samreid** [comment]
I followed @jonathanolson's recommendation, and it seemed straightforward and a good fit for `CanvasLinePlot`.

<details>

```diff
Index: bamboo/js/CanvasLinePlot.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bamboo/js/CanvasLinePlot.js b/bamboo/js/CanvasLinePlot.js
--- a/bamboo/js/CanvasLinePlot.js	(revision 9c0ca2a6d47667fe94c905b6b22ea11502fa32f5)
+++ b/bamboo/js/CanvasLinePlot.js	(date 1608868257033)
@@ -8,7 +8,7 @@
  */
 
 import merge from '../../phet-core/js/merge.js';
-import ColorDef from '../../scenery/js/util/ColorDef.js';
+import PaintColorProperty from '../../scenery/js/util/PaintColorProperty.js';
 import bamboo from './bamboo.js';
 import CanvasPainter from './CanvasPainter.js';
 
@@ -35,18 +35,7 @@
     this.dataSet = dataSet;
 
     // @private
-    this._stroke = null;
-
-    // @private {string|null} - cache values of CSS so they don't need to be recomputed at each paint
-    this._strokeCSS = null;
-
-    // @private
-    this.colorListener = stroke => {
-      this._strokeCSS = ColorDef.toCSS( stroke );
-      assert && assert( typeof this._strokeCSS === 'string' || this._strokeCSS === null );
-    };
-
-    this.setStroke( options.stroke );
+    this.strokePaintColorProperty = new PaintColorProperty( options.stroke );
 
     // @public if you change this directly, you are responsible for calling update on the corresponding ChartCanvasNode
     this.lineWidth = options.lineWidth;
@@ -54,12 +43,7 @@
 
   // @public - Sets the stroke. You are responsible for calling update on the associated ChartCanvasNode(s).
   setStroke( stroke ) {
-    assert && assert( ColorDef.isColorDef( stroke ), 'must be a ColorDef' );
-    if ( stroke !== this._stroke ) {
-      ColorDef.unlink( this._stroke, this.colorListener );
-      this._stroke = stroke;
-      ColorDef.link( this._stroke, this.colorListener ); // caches the new color CSS
-    }
+    this.strokePaintColorProperty.value = stroke;
   }
 
   // @public - see setStroke()
@@ -70,7 +54,7 @@
   // @public
   dispose() {
     assert && assert( !this.isDisposed, 'already disposed' );
-    ColorDef.unlink( this._stroke, this.colorListener );
+    this.strokePaintColorProperty.dispose();
     this.isDisposed = true;
   }
 
@@ -89,19 +73,16 @@
    * @public
    */
   paintCanvas( context ) {
-    assert && assert( typeof this._strokeCSS === 'string' || this._strokeCSS === null, 'stroke must be a CSS string or null' );
-    if ( this._strokeCSS !== null ) {
-      context.beginPath();
-      context.strokeStyle = this._strokeCSS;
-      context.lineWidth = this.lineWidth;
+    context.beginPath();
+    context.strokeStyle = this.strokePaintColorProperty.value.toCSS();
+    context.lineWidth = this.lineWidth;
 
-      for ( let i = 0; i < this.dataSet.length; i++ ) {
-        const point = this.chartTransform.modelToViewPosition( this.dataSet[ i ] );
-        i === 0 && context.moveTo( point.x, point.y );
-        i !== 0 && context.lineTo( point.x, point.y );
-      }
-      context.stroke();
-    }
+    for ( let i = 0; i < this.dataSet.length; i++ ) {
+      const point = this.chartTransform.modelToViewPosition( this.dataSet[ i ] );
+      i === 0 && context.moveTo( point.x, point.y );
+      i !== 0 && context.lineTo( point.x, point.y );
+    }
+    context.stroke();
   }
 }
 
```
</details>

This works great in the Bamboo demo for `?component=ChartCanvasNode`.  However, in Fourier HarmonicsChart.js there is a place that sets a stroke value to be a property: `plot.setStroke( plot.harmonic.colorProperty );`, which fails at runtime.

@jonathanolson does PaintColorProperty support nested `Property` values like PaintDef and ColorDef do?

**Comment by pixelzoom** [comment]
> ... However, in Fourier HarmonicsChart.js there is a place that sets a stroke value to be a property: `plot.setStroke( plot.harmonic.colorProperty );`, which fails at runtime.

I was thinking that it would be nice if `CanvasLinePlot` supported the same types of "color" values as `LinePlot`.  Since `LinePlot extends Path`, that includes `stroke: someColorProperty`.    But since `CanvasLinePlot` has no way to notify its associated `ChartCanvasNode` that a color Property has changed, maybe we don't want to support color Property in `CanvasLinePlot`, and require clients to manage changes to the color Property, like:

```js
const plotColorProperty = new Property( Color.red );
const plot = new CanvasLinePlot( ..., {
  stroke: plotColorProperty.value
} );
const chartCanvasNode = new ChartCanvasNode(..., [  plot ], ...);

// When the plot's color changes...
plotColorProperty.link( plotColor => {
  plot.stroke = plotColor;
  chartCanvasNode.update();
} );

**Comment by samreid** [comment]
I think the recommendation from the preceding comment is good, I considered the alternative of making the CanvasLinePlot aware of its associated `ChartCanvasNode`(s) or vice-versa. I'm happy to apply the patch from https://github.com/phetsims/bamboo/issues/16#issuecomment-751163054.  Would you like me to update Fourier as described in https://github.com/phetsims/bamboo/issues/16#issuecomment-751910556 at the same time?

**Comment by pixelzoom** [comment]
> I'm happy to apply the patch from #16 (comment). Would you like me to update Fourier as described in #16 (comment) at the same time?

Sounds good. There will be some stuff removed from ColorDef too, correct?  Yes please update Fourier.

**Comment by samreid** [comment]
In the commits I converted `CanvasLinePlot` to use `PaintColorProperty` and updated Fourier accordingly.  I split up the update function so that the strokes could be updated independently.  It appeared to be working properly in my testing, but I am not fully familiar with this sim, so please test again.  These commits are ready for review.

> There will be some stuff removed from ColorDef too, correct?

The additions made to ColorDef seem like they may one day be useful, even though they are unconventional.  Still, since we don't have an immediate need for them, I'll remove them for now.

**Comment by pixelzoom** [comment]
> In the commits I converted CanvasLinePlot to use PaintColorProperty and updated Fourier accordingly. I split up the update function so that the strokes could be updated independently. It appeared to be working properly in my testing, but I am not fully familiar with this sim, so please test again.

If you're not familiar with a sim, it's generally not a good idea to change logic that you don't need to touch. 
In this case, stroke and lineWidth are never to be updated independently, they always update together.  This change was unnecesary and undesirable. More importantly, it's making it difficult for me to identify what was actually necessary to change.

**Comment by samreid** [comment]
Are you saying that if a `harmonicPlot.colorProperty` changes, you would like to set the strokes to their current values?  I'm happy to recombine the updates if you think it's better for the sim, reassign me if you would like me to do something like that.

**Comment by pixelzoom** [comment]
Yes. Reverted in the previous commit.

Reviewing the changes to CanvasLinePlot.

- [ ] setStroke is missing doc for `@param stroke`.  What types are acceptable for stroke - ColorDef, PaintDef, some subset? Since you're using PaintColorProperty, I would have expected this to be OK:

` plot.setStroke( plot.harmonic.colorProperty );` 

but it fails, and you changed to:

` plot.setStroke( plot.harmonic.colorProperty.value );`

**Comment by pixelzoom** [comment]
> Are you saying that if a harmonicPlot.colorProperty changes, you would like to set the strokes to their current values?

Oh I see... You're saying that I need to call setStroke if colorProperty changes -- which can happen via colors.html or (perhaps) PhET-iO.   Yes, I need to handle that.  But no, I don't feel the need to break emphasizedHarmonicsListener into a bunch of little functions.

**Comment by samreid** [comment]
In the commit, I added PaintDef support in CanvasLinePlot.setStroke and added documentation.  I updated Fourier to call with `plot.setStroke( plot.harmonic.colorProperty );` instead of `plot.setStroke( plot.harmonic.colorProperty.value );`.  The last part that's missing is a call to `chartCanvasNode.update();` if a `colorProperty` value changes. Would you like me to add that part?

**Comment by pixelzoom** [comment]
> ... Yes, I need to handle that.  ...

It was already handled elsewhere. I factored it out so that it's more obvious.

**Comment by samreid** [comment]
> It was already handled elsewhere. I factored it out so that it's more obvious.

I see it now, thanks!

**Comment by pixelzoom** [comment]
In the above commit, I chose to use `colorProperty.value` wherever `setStroke` is called.  

I find this to be confusing:

```js
      const colorProperty = new Property( Color.black );
      const plot = new CanvasLinePlot( ..., {
        stroke: colorProperty // this causes plot to listen to colorProperty
      } ); 
      const chartCanvasNode = new ChartCanvasNode( ..., [ plot ], ... );
      // CanvasLinePlot is observing colorProperty, so we only need to call update.
      colorProperty.lazyLink( () => chartCanvasNode.update() );
```

It suspect that developers won't totally understand what is going on with stroke and PaintColorProperty, and will tend to write of these dubious listeners:

```js
      colorProperty.lazyLink( color => { 
        plot.setStroke( color );  // this causes plot to no longer listen to colorProperty
        chartCanvasNode.update() 
     } );

// or
      colorProperty.lazyLink( () => { 
        plot.setStroke( colorProperty ); // this does nothing because useDeepEquality: false in CanvasLinePlot
        chartCanvasNode.update() 
     } );
```

This feels clearer and less error-prone:

```js
      const colorProperty = new Property( Color.black );
      const plot = new CanvasLinePlot( harmonic, this.chartTransform, [], {
        stroke:  colorProperty.value
      } ); 
      const chartCanvasNode = new ChartCanvasNode( ..., [ plot ], ... );
      colorProperty.lazyLink( color => {  
        plot.stroke = color;
        chartCanvasNode.update(); 
      } );
```

So... And I'm thinking that we might want to revert PaintColorProperty, and restrict stroke to be `{Color|string|null}`.   And if not, I'll probably avoid passing a stroke Property to CanvasLinePlot, because imo it tends to obfuscate things.

**Comment by pixelzoom** [comment]
@samreid and I discussed the above comment, and agreed that constraining stroke to {Color|string|null} would be preferrable.  I made some good progress on that, then got bogged down in the inconsistencies of how "color" is handled by Color, ColorDef, PaintDef, PaintColorProperty, etc.   I briefly discussed with @jonathanolson on Slack, but he's not up to speed.  So I bailed.

**Comment by samreid** [comment]
Here's an implementation that uses `{Color|string|null}` (full file, not a diff).  It also caches the CSS for high performance.

<details>

```js
// Copyright 2020, University of Colorado Boulder

/**
 * CanvasLinePlot renders a {Array<Vector2|null>} dataSet on a canvas that is managed by a ChartCanvasNode.
 * Typically it is preferable to use LinePlot, but this alternative is provided for cases where canvas must be
 * used for performance. Like LinePlot, null values are skipped, and allow you to create gaps in a plot.
 * @see LinePlot
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */

import merge from '../../phet-core/js/merge.js';
import Color from '../../scenery/js/util/Color.js';
import bamboo from './bamboo.js';
import CanvasPainter from './CanvasPainter.js';

class CanvasLinePlot extends CanvasPainter {

  /**
   * @param {ChartTransform} chartTransform
   * @param {Array<Vector2|null>} dataSet
   * @param {Object} [options]
   */
  constructor( chartTransform, dataSet, options ) {

    options = merge( {
      stroke: 'black', // {Color|string|null}
      lineWidth: 1
    }, options );

    super();

    // @private
    this.chartTransform = chartTransform;

    // @public if you change this directly, you are responsible for calling update on the corresponding ChartCanvasNode
    this.dataSet = dataSet;

    // @public if you change this directly, you are responsible for calling update on the corresponding ChartCanvasNode
    this.lineWidth = options.lineWidth;

    // @private - CSS for rendering the stroke
    this.strokeCSS = null; // updated in setStroke
    this.setStroke( options.stroke );
  }

  /**
   * Sets the stroke.
   * @param {Color|string|null} stroke - If you call setStroke, you are responsible for calling update on the associated ChartCanvasNode(s).
   * @public
   */
  setStroke( stroke ) {
    assert && assert( stroke instanceof Color || typeof stroke === 'string' || stroke === null, 'invalid stroke' );
    this.strokeCSS = stroke instanceof Color ? stroke.toCSS() : stroke;
  }

  // @public - see setStroke()
  set stroke( stroke ) {
    this.setStroke( stroke );
  }

  // @public
  dispose() {
    assert && assert( !this.isDisposed, 'already disposed' );
    this.isDisposed = true;
  }

  /**
   * Sets dataSet. You are responsible for calling update on the associated ChartCanvasNode(s).
   * @param {Vector2[]} dataSet
   * @public
   */
  setDataSet( dataSet ) {
    this.dataSet = dataSet;
  }

  /**
   * Intended to be called by ChartCanvasNode.
   * @param {CanvasRenderingContext2D} context
   * @public
   */
  paintCanvas( context ) {
    context.beginPath();

    if ( this.strokeCSS ) {
      context.strokeStyle = this.strokeCSS;
      context.lineWidth = this.lineWidth;

      let moveToNextPoint = true;

      // Only access the data set length once for performance
      const length = this.dataSet.length;
      for ( let i = 0; i < length; i++ ) {

        const dataPoint = this.dataSet[ i ];
        assert && assert( dataPoint === null || dataPoint.isFinite(), 'data points must be finite Vector2 or null' );

        // Draw a line segment to the next non-null value. Null values result in a gap (via move) in the plot.
        if ( dataPoint ) {
          const viewPoint = this.chartTransform.modelToViewPosition( dataPoint );
          if ( moveToNextPoint ) {
            context.moveTo( viewPoint.x, viewPoint.y );
            moveToNextPoint = false;
          }
          else {
            context.lineTo( viewPoint.x, viewPoint.y );
          }
        }
        else {
          moveToNextPoint = true;
        }
      }
      context.stroke();
    }
  }
}

bamboo.register( 'CanvasLinePlot', CanvasLinePlot );
export default CanvasLinePlot;
```

</details>

@pixelzoom does that look OK to you?  Will Fourier need to be updated if we go with this approach?

**Comment by pixelzoom** [comment]
Looks good, but I would suggest one change:

```diff
- assert && assert( stroke instanceof Color || typeof stroke === 'string' || stroke === null, 'invalid stroke' );
+ assert && assert( stroke instanceof Color || ( typeof stroke === 'string' && Colorr.isCSSString( stroke ) ) || stroke === null, 'invalid stroke' );
```

I've confirmed that no changes to Fourier are required.

**Comment by samreid** [comment]
I made the change (with the CSS string test) and tested in Fourier.  No problems noted, closing.
