### ISSUE TITLE
rename ChartModel to ChartTransform, and other enhancements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#18]
@samreid and I decided that ChartTransform is a more appropriate name, since (a) it defines the model and view coordinate systems, and the methods to transform between them, and (b) in keeping with bamboo philosophy of "small components" it will keep responsibilities limited to this transform.

<details>
<summary>Slack discussion</summary>

Chris Malley  11:07 AM
Wondering if ChartModel should be renamed to ChartTransform?

Sam Reid  11:09 AM
That is a reasonable question.  I think that ChartTransform is mostly appropriate, but that doesn’t indicate that it has things like width and height

Chris Malley  11:10 AM
It has dimensions for view (width, height) and model (modelXRange, modelYRange), as well as some scaling features that need better doc.
11:12
And I could argue that it should be using (or maybe even extending) ModelViewTransform2.

Sam Reid  11:13 AM
 And I could argue that it should be using (or maybe even extending) ModelViewTransform2.
One thing JO recommended which has been working very well is to treat the axes independently.  So you can change the x-axis domain without having to set the same y-axis range to itself.

Chris Malley  11:13 AM
ChartModel is too broad, and provides the temptation to add more stuff to it that is not related to chart size and transforms.  In keeping with bamboo philosophy of "small components", I think ChartTransform would be more likely to keep it small. (edited) 
11:13
OK, I'm convinced about no ModelViewTransform2.

Sam Reid  11:14 AM
I’d be OK with ChartTransform.  I agree it isn’t just about “model” things, unless we are thinking of it as a “view model”

Chris Malley  11:14 AM
ChartModel is also confusing in the context of a sim like Fourier, where there is a much more complicated "chart model".
11:15
It's not a view model.  It defines the model and view coordinate systems, and the methods to transform between them.

Sam Reid  11:15 AM
It’s OK with me if you rename it to ChartTransform , I’m convinced

Chris Malley  11:16 AM
Great, will do.

Sam Reid  11:16 AM
:thumbsup:

</details>

**Comment by pixelzoom** [comment]
In above commits:
* renamed ChartModel to ChartTransform
* renamed chartModel to chartTransform throughout bamboo and clients

This looks so much nicer to me in context.

Over to @samreid to take a peek, feel free to close.

**Comment by pixelzoom** [comment]
A couple of other suggestions for ChartTransform:

* Rename `width` and `height`  to `viewWidth` and `viewHeight`, so that names are qualified for both model and view.

* Can `width` and `height` be moved to options?  It would make call sites clearer.  Or maybe I don't understand why it OK to have defaults for `modelXRange` and `modelYRange` but not the view quantities?

**Comment by pixelzoom** [comment]
Another suggestion...

`link` and `unlink` seem like the wrong API for ChartTransform.  `link` is specific to Property, and what this actually does is add a listener to an Emitter, which is typically done via `addListener`.  Similarly for `unlink`, which actually does a `removeListener`.  So `link` and `unlink` seem "off" for this API.  

Let's rename `this.transformChangedEmitter` to `this.changedEmitter`, because "transform" is now redundant since this is ChartTransform.  Then rename `link` to `addChangedListener`, `unlink` to `removeChangeListener`.   Sound OK?

**Comment by pixelzoom** [comment]
Why do we need that? This is an Emitter, why don't we use the same API as Emitter?

**Comment by pixelzoom** [comment]
100% of the calls to `chartTransform.link` are in constructors for bamboo components, and look like this:

```js
    const update = () => this.updateAxisNode();
    chartTransform.link( update );
```

The revised API would look like this:

```js
    const update = () => this.updateAxisNode();
    chartTransform.addListener( update );
    update();
```

**Comment by pixelzoom** [comment]
If we're going to sick with `link`, then we need `lazyLink`.   Similar to use of Property lazyLink, if my chart component is initialized properly, why do I need to do unnecessary work when linking to a ChartTransform?

**Comment by pixelzoom** [comment]
`this.transformChangedEmitter` is currently `@public`.  Assuming that was an intentional choice... If we're going to expose that this is an Emitter, why bother with link and unlink?

**Comment by pixelzoom** [comment]
Renaming `transformChangedEmitter` to `changedEmitter` doesn't seem controversial, so I did so in the above commit.

I think we should delete the `link` and `unlink` methods, and (since it's public) have clients use `this.changedEmitter` directly.

**Comment by samreid** [comment]
> 100% of the calls to chartTransform.link/unlink are in constructors for bamboo components,

Yes, that's true at the moment, but I expect the proliferation of many sim-specific bamboo components, so we should choose something that is clear and can be widely used.

I didn't feel like `link` was a great fit for it, but I did like pairing together the `addListener` and `listener()` call was a nice step.  But maybe it is not necessary, or maybe there is a better way to accomplish it.

> I think we should delete the `link` and `unlink` methods, and (since it's public) have clients use `this.changedEmitter` directly.   Then there's no question about what the expected behavior is, and no confusing mixture of Property & Emitter interfaces.

That's OK with me.

**Comment by pixelzoom** [comment]
Another suggestion for improvement...

"X" and "Y" appear throughout the API and mean horizontal and vertical respectively. `modelXRange`, `modelYRange`, `xScale`, `yScale`, and their setters and getters.  So I don't see the advantage in having methods that require an Orientation, like:

```js
  modelToView( axisOrientation, value ) {
    assert && assert( axisOrientation === Orientation.VERTICAL || axisOrientation === Orientation.HORIZONTAL );
    const modelRange = axisOrientation === Orientation.HORIZONTAL ? this.modelXRange : this.modelYRange;
```

The first thing they do is map to some public "X" or "Y" field (in this case `modelXRange` or `modelYRange`).  So why not just have:

```js
moveToViewX( modelX ) {...}
modelToViewY( modelY ) {...}
```

This is also more similar to the familiar ModelViewTransform2 API.

**Comment by samreid** [comment]
There are 7 call sites where the dimension is a variable like so:

```js
const viewValue = this.chartTransform.modelToView( this.axisOrientation.opposite, this.value );
```

How do you recommend to write those 7 call sites?

**Comment by pixelzoom** [comment]
In the above commit:

* Deleted ChartTransform `link` and `unlink` and access `this.changedEmitter` directly in clients.
* Renamed `update{{CLASS_NAME}}` method to `update`, so that naming is consistent throughout bamboo.

**Comment by pixelzoom** [comment]
@samreid asked:
> How do you recommend to write those 7 call sites? [of `modelToView`]

I see what you mean. 

As a compromise, I've added these convenience methods:

```js
  modelToViewX( value ) {
    return this.modelToView( Orientation.HORIZONTAL, value );
  }

  modelToViewY( value ) {
    return this.modelToView( Orientation.VERTICAL, value );
  }
```

**Comment by pixelzoom** [comment]
OK, I think the remaining things to hit in this issue are from https://github.com/phetsims/bamboo/issues/18#issuecomment-743393567:
> * Rename `width` and `height` to `viewWidth` and `viewHeight`, so that names are qualified for both model and view.
> 
> * Can `width` and `height` be moved to options? It would make call sites nicer. Or maybe I don't understand why it OK to have defaults for `modelXRange` and `modelYRange` but not the view quantities?

I'd like to do both of these. @samreid any objections?

**Comment by samreid** [comment]
Renaming to width/height sounds good.

I thought viewWidth and viewHeight should be required since there are no reasonable defaults.  But that would make a more symmetrical API.  I'm not even confident about the default modelXRange and modelYRange.  What about moving the modelXRange and modelYRange to be required parameters?  I don't feel too strongly either way about this.

**Comment by pixelzoom** [comment]
I would pick one of these:

`new ChartTransform(viewWidth,viewHeight,modelXRange,modelYRange,options)`

`new ChartTransform( {
   viewWidth: ...,
   viewHeight: ...,
   modelXRange: ...,
   modelYRange, ...,
} );
`

In the latter, the parameter could be either `options` or `config`.  

Which do you think is clearer?

**Comment by pixelzoom** [comment]
I would pick one of these:

```js
new ChartTransform( 200, 100, new Range( -2 * L, 2 * L ), new Range( -1.5, 1.5 ), options );
```

````js
new ChartTransform( {
   viewWidth: 200,
   viewHeight: 100,
   modelXRange: new Range( -2 * L, 2 * L ),
   modelYRange: new Range( -1.5, 1.5 ),
} );
`

In the latter, the parameter could be either `options` or `config`.  

Which do you think is clearer?

**Comment by pixelzoom** [comment]
@samreid FYI... A few cleanup-related commits above, before I rename `width` and `height` to `viewWidth` and `viewHeight`.

**Comment by pixelzoom** [comment]
Renaming of `width` and `height` to `viewWidth` and `viewHeight` was completed in https://github.com/phetsims/bamboo/commit/9a875beeb0a8a1cd1ea190754c9b7bd06856be0f.

The other commits above are documentation.   And d243ca9 is a continuation of what I suggested in https://github.com/phetsims/bamboo/issues/18#issuecomment-743521843.

**Comment by pixelzoom** [comment]
In the above commit, I took a stab at documenting `forEachSpacing`.  @samreid have a look, feel free to revise.

**Comment by pixelzoom** [comment]
`axisOrientation` is validated in a few places. I stuck with what was originally in the code, but added an assertion message:

```js
    assert && assert( axisOrientation === Orientation.HORIZONTAL || axisOrientation === Orientation.VERTICAL,
      `invalid axisOrientation: ${axisOrientation}` );
```

I'm wondering why you chose to check specific values, instead of this:

```js
    assert && assert( Orientation.includes( axisOrientation ), `invalid axisOrientation: ${axisOrientation}` );
```

Is there concern that Orientation may someday have values other than HORIZONTAL and VERTICAL?

**Comment by pixelzoom** [comment]
Re ChartTransform's constructor signature...  I looked at usages of `new ChartTransform`.  Most looked like this one in CCKCChartNode.js:

```js
    const chartTransform = new ChartTransform( 150, 100, {
      modelXRange: new Range( 0, 4.25 ),
      modelYRange: new Range( -2, 2 )
    } );
```

If we use constructor parameters, that becomes:

```js
    const chartTransform = new ChartTransform( 150, 100, new Range( 0, 4.25 ), new Range( -2, 2 ) );
```

If we use options:

```js
    const chartTransform = new ChartTransform( {
      viewWidth: 150,
      viewHeight: 100,
      modelXRange: new Range( 0, 4.25 ),
      modelYRange: new Range( -2, 2 )
    } );
```

For someone reading this code, the options approach is clearly superior.  And I'm not locked into a specific order of arguments -- if I want to specify model before view, I can do so. 

So I took the liberty of going with the options approach, and ChartTransform's constructor API now looks like this:

```js
  /**
   * @param [options]
   */
  constructor( options ) {

    options = merge( {

      // The horizontal axis is referred to as the "x" axis, though it may be used to depict another dimension, such as "time"
      viewWidth: 100, // {number} width in view coordinates
      modelXRange: new Range( -1, 1 ), // {Range} range of the x axis, in model coordinates
      xScale: x => x, // {function(number):number} model-to-view scaling function for the x axis

      // The vertical axis is referred to as the "y" axis, though it may be used to depict another dimension such as "width"
      viewHeight: 100, // {number} height in view coordinates
      modelYRange: new Range( -1, 1 ), // {Range} range of the y axis, in model coordinates
      yScale: y => y // {function(number):number} model-to-view scaling function for the y axis
    }, options );
```

Happy to discuss further if you feel that this is the wrong direction.

**Comment by pixelzoom** [comment]
Back over to @samreid for review.  Here's what needs doing:

- [ ] Review misc cleanup commits (if you want to), starting with the ones mentioned in https://github.com/phetsims/bamboo/issues/18#issuecomment-743924069.

- [ ] Review the rename of `viewWidth` and `viewHeight`.

- [ ] Review the documentation for `forEachSpacing`, revise if needed.

- [ ] Decide whether assertion expressions can be changed to `Orientation.includes( axisOrientation )`, see https://github.com/phetsims/bamboo/issues/18#issuecomment-743928995.

- [ ] Weigh in on whether moving `viewWidth` and `viewHeight` to options looks OK.

**Comment by samreid** [comment]
> Is there a concern that Orientation might someday have values other than HORIZONTAL and VERTICAL?

No, the `includes` check seems preferable.

**Comment by pixelzoom** [comment]
Changed to `Orientation.includes` in the above commit. 

Final observation... ChartTransform is currently a one-way transform. It supports model-to-view, but not view-to-model. I guess we'll address that when it's needed, like when someone needs to click on a charge and know what the corresponding model point is.

Closing.
