### ISSUE TITLE
incomplete comment in ChartTransform

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#20]
This incomplete comment followed by blank lines was introduced into ChartModel (now ChartTransform) in 9629ef4cf446cffd065cf16060be24d1dfe41e31:

```js
    // for a log plot, we need to choose a scale factor that takes


    let scaledValue = scale( value );
    if ( isNaN( scaledValue ) || !Number.isFinite( scaledValue ) ) {
      scaledValue = value;
    }
```

I'm not sure how to fix this comment.  @samreid can you please clean this up?

**Comment by samreid** [comment]
I removed the unnecessary comment fragment, closing.
