### ISSUE TITLE
SpanNode: add options for subcomponents ArrowNode and Line

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#22]
Related to #19 ...

Options for the ArrowNode used in SpanNode are currently hardcoded.  This is an aspect of SpanNode that is highly likely to be sim-specific, and is a good place to use nested options (`arrowNodeOptions`).

**Comment by pixelzoom** [comment]
Ditto for the length of the `Line` instances that appear at the ends of the arrow heads.

**Comment by samreid** [comment]
Implemented and ready for review.

**Comment by pixelzoom** [comment]
Question about this:

```js
    if ( assert && options && options.arrowNodeOptions ) {
      assert && assert( !options.arrowNodeOptions.hasOwnProperty( 'stroke' ), 'Stroke not supported for inner arrow, use fill' );
      assert && assert( !options.arrowNodeOptions.hasOwnProperty( 'lineWidth' ), 'lineWidth not supported for inner arrow, use fill' );
    }
...
    options = merge( {
        ...
        lineWidth: 0, // Not supported since it throws off the dimensions, use fill instead
        stroke: null // Not supported since it throws off the dimensions, use fill instead
      }
    }, options );
```

Why is `lineWidth: 0` necessary?  If should be sufficient to set `stroke: null`.

And if `lineWidth: 0` is for some reason necessary, then the assertions should be moved _after_ the `merge` call, to prevent introducing an error via future programming changes.  I.e.:

```js
assert && assert( options.lineWidth === 0, 'lineWidth not supported for inner arrow, use fill' );
assert && assert( options.stroke === null, 'stroke not supported for inner arrow, use fill' );
```

But I suspect that `lineWidth` is irrelevant, and this is sufficient:

```js
    options = merge( {
        ...
        stroke: null // Not supported since it throws off the dimensions, use fill instead
      }
    }, options );

    assert && assert( options.stroke === null, 'stroke not supported for inner arrow, use fill' );
```

**Comment by samreid** [comment]
Thanks for the recommendations.  I agree `strokeWidth: 0` is unnecessary. I also moved the assertions after the merge call. 
 The default `stroke` in ArrowNode is non-null, so I we must set it somewhere in SpanNode.  Committing shortly, then will be ready for re-review.

**Comment by pixelzoom** [comment]
Looks nice, closing.
