### ISSUE TITLE
ChartTransform enhancements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#24]
ChartTransform has some duplication, and would be nice to have `modelToViewXY` to avoid having to create a Vector2 to pass to `modelToViewPosition`, and for symmetry with ModelViewTransform2.

I'll do this.

**Comment by pixelzoom** [comment]
Done.  I added `modelToViewXY` and fixed some duplication in `modelToViewPosition`. 

Over to @samreid for review.

**Comment by samreid** [comment]
I reviewed the commits and don't have any recommendations, thanks!  Closing.
