### ISSUE TITLE
LinePlot vs StraightLinePlot

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#25]
Today I created `StraightLinePlot`, to demonstrate for a Google Group member how to create additional plot types.  It plots _y = mx + b_. In deciding how to name it, I felt a bit of name (and conceptual) collision with `LinePlot`. 

I think `LinePlot` is probably correctly named, see https://en.wikipedia.org/wiki/Line_chart:
> A **line chart** or **line plot** or **line graph** or **curve chart** is a type of chart which displays information as a series of data points called 'markers' connected by straight line segments. It is a basic type of chart common in many fields.

@samreid Suggestions? Better name for `StraightLinePlot`?  Different name for `LinePlot`? Do nothing?

**Comment by samreid** [comment]
Looks good, thanks!  I think LinePlot is already well-named, I'm not too worried about the name `StraightLinePlot`, but what do you think of `LinearEquationPlot`?

**Comment by pixelzoom** [comment]
Thanks for the feedback. I like `LinearEquationPlot`.  I'll rename and notify the Google Group user.

**Comment by pixelzoom** [comment]
Done, closing.
