### ISSUE TITLE
ChartCanvasNode demo looks messed up

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#26]
@samreid is the bamboo demo for ChartCanvasNode supposed to look like this?

<img width="1068" alt="screenshot_912" src="https://user-images.githubusercontent.com/3046552/111080261-4a999380-84c3-11eb-978b-b05ddd4eb6f8.png">

**Comment by samreid** [comment]
Yes, it's a demo for missing data.  But we could move that to a separate labeled test so it's not confusing if that would help.

**Comment by pixelzoom** [comment]
OK, gotcha.   At the very least, that should be documented in the code.

And I think that perhaps we should carve out some time to clean up the bamboo demos.  Some of these demos are confusing because they aren't really demos of one or two specific things, they are testing a bunch of things.  For example, testing SpanNode in DemoLinePlot.

**Comment by pixelzoom** [comment]
Doc looks good, and I think it's a nice change to only have a hole in 1 plot -- it looks less like a bug.

> To me, it makes sense to show the SpanNode in the context of a fuller plot, how do you recommend to organize this? Please open a new issue for that depending on your recommendation.

I'm not suggesting that things should not be showing in context.  What I'm pointing out is that there is generally too much going on in some of these demos, and some components (like SpanNode) cannot be selected via the combo box.   I'll create a new GitHub issue for "clean up demos".
