### ISSUE TITLE
Q2 Goal: Make sure foundation of bamboo is ready for general use

### ISSUE THREAD

**Issue by samreid** [phetsims/bamboo#29]
During the 2021 Q2 planning session, we agreed we want to make sure bamboo foundation is ready for general use.  We will get a better sense of this during Fourier Screen 3 development.

This does not mean we need all the components we will ever need, or to have everything fixed, but mainly that it is at a good foundation.

**Comment by pixelzoom** [comment]
Reviewed at Q3 planning meeting. This epic was accomplished in Q2, and can be closed.
