### ISSUE TITLE
BarPlot won't draw new lines after setDataSet

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bamboo#30]
The implementation of setDataSet is
```js
  setDataSet( dataSet ) {
    this.dataSet = dataSet;
    this.update();
  }
```

The implementation of `update` iterates over the `lines` array which is set only on construction. The result is that `update` won't add any new Lines that may get added with `setDataSet`.  A patch like this fixes the problem though there may be a more efficient way. Would something like this work?

```patch
Index: js/BarPlot.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/BarPlot.js	(revision 315c4c5b03a5e5918f3b9cd43ed0099f3c68625e)
+++ js/BarPlot.js	(date 1620258534392)
@@ -59,7 +59,13 @@
    * @public
    */
   setDataSet( dataSet ) {
+    this.lines.forEach( node => this.removeChild( node ) );
+
     this.dataSet = dataSet;
+
+    this.lines = dataSet.map( () => new Line( 0, 0, 0, 0, { lineWidth: 10 } ) );
+    this.lines.forEach( node => this.addChild( node ) );
+
     this.update();
   }
```

**Comment by samreid** [comment]
I started with the patch and factored out some duplicated logic.  I added a test harness in the bamboo example.  @jessegreenberg can you please review?

Also, in the slack thread, the sample picture showed a stroke around each bar--I don't think that's supported with BarPlot.  I'm wondering if BarPlot should be changed to use `Rectangle`? or if we should add a separate type for that?  Can you open a separate issue and recommend how to proceed?

**Comment by jessegreenberg** [comment]
The change is working great, thanks @samreid! `setDataSet` looks good.

You are correct, I will create a new issue for bar strokes, and close this one.
