### ISSUE TITLE
Add strokes to BarPlot bars

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bamboo#31]
In Greenhouse Effect I have need for a plot like 
![image](https://user-images.githubusercontent.com/6396244/117319896-bb24b700-ae59-11eb-990e-9a4f872d05b9.png)

Bamboo's BarPlot is working great for this, but the mockup shows strokes around each bar which isn't currently supported. BarPlot bars use currently Line which only have a stroke for the entire bar. The most straightforward way to support would be to use Rectangles instead, I will try that.

**Comment by jessegreenberg** [comment]
I made this change so that BarPlot draws with Rectangle instead of Line. @samreid would you mind reviewing? Just listing out the specific things that seem important for the reviewer to check:
- Since Rectangle doesn't support negative height I had to set the bar `bottom` to the plot y=0 line if it has a negative height.
- I added an option for `barWidth` to control width of bars in view coords
- I converted `pointToColor` option to `pointToPaintableFields` so that fill, stroke, and other Paintable options can be set.
- `pointToPaintableFields` was the name I landed on because `merge` would have tried to merge `pointToPaintableOptions`.
- I needed an `eslint-disable-line` for the default `pointToPaintableFields` because it returns an object on one line. Maybe there is better syntax for this.

**Comment by samreid** [comment]
Looks great, I tested this in the bamboo demo and in greenhouse gases.  Some ideas for improvements:

The code in update may be simpler (avoid the if statement) if we use Math.min like so:

```js
      // rectangles cannot have negative height
      const rectHeight = tip.y - tail.y;
      const bottom = Math.min( tail.y, tip.y );
      this.rectangles[ i ].setRect( tail.x - this.barWidth / 2, bottom, this.barWidth, Math.abs( rectHeight ) );
```

> - I needed an `eslint-disable-line` for the default `pointToPaintableFields` because it returns an object on one line. Maybe there is better syntax for this.

Could be addressed like so:

```js
const DEFAULT_PAINT_OPTIONS = { fill: 'black' };

// ...
pointToPaintableFields: point => DEFAULT_PAINT_OPTIONS
```

What if we wanted the bar width to also be a function of the data point?  It's unclear where we should draw the line for customization.  But the most general would be a mutateRectangle function that takes a dataPoint and a Rectangle, and can adjust it accordingly (setting color, stroke, width, etc).  But this API may be less friendly (less structural?).  What do you recommend?

**Comment by jessegreenberg** [comment]
Thanks for reviewing @samreid! Improvements made in the above commits.

> What if we wanted the bar width to also be a function of the data point

I don't think I would recommend pursuing this. I did a search through bar plot examples and couldn't find a plot that looked like this. I would recommend we wait until this is requested because in my opinion it seems like an unlikely case.

**Comment by samreid** [comment]
I searched "bar chart where bars are different colors" and saw many examples of bar charts where each bar is a different color.  Is that worth pursuing?

**Comment by jessegreenberg** [comment]
"bar chart where bars are different colors" seems very useful and is supported by `pointToPaintableFields`. I did a search for "bar chart where bars are different widths" and didn't see many examples in the wild.

**Comment by samreid** [comment]
Excellent, thanks for helping me understand.  The commits seem good, can this issue be closed?

**Comment by jessegreenberg** [comment]
Great, I think so, thanks @samreid!
