### ISSUE TITLE
BarPlot this.dataSet should not be public

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#33]
In BarPlot, public `this.dataSet` looks buggy to me:

```js
    // @public if you change this directly, you are responsible for calling update
    this.dataSet = dataSet;
```

Method `setDataSet` is doing some important work.  So if you set it directly and call `update`, `this.rectangles` will not have been updated.

**Comment by pixelzoom** [comment]
Slack:

Chris Malley  3:25 PM
Actually…. In BarPlot, public this.dataSet looks buggy to me. If you don’t use setDataSet, then this.rectangles won’t be updated. (edited) 

Jesse Greenberg  3:26 PM
True, I am not sure why it is public with setDataSet. But the comment for it acknowledges that.

Chris Malley  3:30 PM
The idea is to be able to mutate Vector2 instances in the dataSet, then call update.  LinePlot’s setDataSet method has documentation that makes this clear:

```js
  /**
   * Sets the dataSet and redraws the plot. If instead the dataSet array is mutated, it is the client's responsibility
   * to call `update` or make sure `update` is called elsewhere (say, if the chart scrolls in that frame).
   * @param {Vector2[]} dataSet
   * @public
   */
  setDataSet( dataSet ) {
```

BarPlot was probably copy-pasted from LinePlot.

BarPlot could also be fixed by moving  stuff out of setDataSet and into update.

**Comment by samreid** [comment]
This problem was introduced in https://github.com/phetsims/bamboo/issues/30.  Here's a patch that should solve it:

<details>

```diff

Index: js/BarPlot.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/BarPlot.js b/js/BarPlot.js
--- a/js/BarPlot.js	(revision 79084b091cedb969849aaefc4ee2d2616c649b27)
+++ b/js/BarPlot.js	(date 1623711506430)
@@ -66,13 +66,7 @@
    * @public
    */
   setDataSet( dataSet ) {
-    this.rectangles.forEach( rectangle => this.removeChild( rectangle ) );
-
     this.dataSet = dataSet;
-
-    this.rectangles = dataSet.map( () => new Rectangle( 0, 0, 0, 0 ) );
-    this.rectangles.forEach( rectangle => this.addChild( rectangle ) );
-
     this.update();
   }
 
@@ -80,6 +74,20 @@
    * @public
    */
   update() {
+
+    // Add one rectangle per data point
+    while ( this.rectangles.length < this.dataSet.length ) {
+      const rectangle = new Rectangle( 0, 0, 0, 0 );
+      this.rectangles.push( rectangle );
+      this.addChild( rectangle );
+    }
+
+    // If data points were removed, also remove rectangles
+    while ( this.dataSet.length < this.rectangles.length ) {
+      const rectangle = this.rectangles.pop();
+      this.removeChild( rectangle );
+    }
+
     for ( let i = 0; i < this.rectangles.length; i++ ) {
       const tail = this.chartTransform.modelToViewPosition( new Vector2( this.dataSet[ i ].x, 0 ) );
       const tip = this.chartTransform.modelToViewPosition( this.dataSet[ i ] );

```

</details>

@jessegreenberg can you please review the patch?

**Comment by jessegreenberg** [comment]
That looks very nice, thanks. I applied the patch and then tested it in the bamboo demo by adding this change and then pressing the "Random Data Set" button and seeing the rectangles get added and removed.
<details>

```patch
Index: js/demo/DemoBarPlot.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/demo/DemoBarPlot.js	(revision 038ecc842d0c854278cd3d91df559532b2415e99)
+++ js/demo/DemoBarPlot.js	(date 1623716323647)
@@ -32,7 +32,8 @@
 
     const createDataSet = ( randomX, randomY ) => {
       const dataSet = [];
-      for ( let i = 0; i <= 24; i++ ) {
+      const randomNum = dotRandom.nextInt( 23 );
+      for ( let i = 0; i <= randomNum; i++ ) {
         const x = Math.PI * i;
         const arg = x - Math.PI * 12;
         const c = 10;
```
</details>

@samreid  back to you, anything else for this?

**Comment by samreid** [comment]
Thanks, looks good.  Reassigning to @pixelzoom so he is aware, and in case he wants to do additional code review.

**Comment by pixelzoom** [comment]
Looks good.  I updated the doc for `setDataSet` to be the same as for other plots. That is, it gives more detail about when and why you need to call `update.

Closing.
