### ISSUE TITLE
Should bamboo plots be moved to a "plots/" subdirectory?

### ISSUE THREAD

**Issue by samreid** [phetsims/bamboo#36]
Inspired by #34 and #35 it seems possible that we will have a proliferation of plot types in bamboo.  Should these be moved to a "plots" subdirectory, or is it preferable to keep everything top-level?

@pixelzoom what do you recommend?

**Comment by pixelzoom** [comment]
I don't feel strongly either way. 

I have been wondering if there should be a Plot.js base class, since there's starting to be duplication, as well as some undesirable variation, amoung the plot classes.  Maybe a new issue?

**Comment by samreid** [comment]
I'll consider this after factoring out a plot supertype in #35

**Comment by samreid** [comment]
I don't feel strongly about putting Plots in a subdirectory.  Maybe in the future if there are too many things, we can reconsider.  Closing.
