### ISSUE TITLE
Plot base class

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#37]
I have been wondering if there should be a Plot.js base class. There's starting to be duplication, as well as some undesirable variation, amoung the plot classes.  And if you're trying to create a new plot class, it's not totally clear what the required interface/API is.

@samreid thoughts?

**Comment by samreid** [comment]
I opened https://github.com/phetsims/bamboo/issues/35 to factor out commonalities between existing Plot classes.  I'll add your comment there and close this as a duplicate.
