### ISSUE TITLE
How should we handle data points outside of a transform's domain?

### ISSUE THREAD

**Issue by samreid** [phetsims/bamboo#48]
In https://github.com/phetsims/bamboo/issues/40#issuecomment-931454309 @pixelzoom said:

> Question about this bit of code in `modelToView`, which is not new:
> 
```js
101 let transformedValue = transform.evaluate( value );
    if ( isNaN( transformedValue ) || !Number.isFinite( transformedValue ) ) {
      transformedValue = value;
    }
```
> 
> Do you recall why this is needed? Should it be documented?

**Comment by samreid** [comment]
This was introduced for https://github.com/phetsims/bamboo/issues/3, and is exercised for the bamboo demo "Multiple Plots" when you select "log" scale.  It seems the problem is when trying to evaluate a value outside of a function's domain.  I'm not sure what to do about this case.  What do you recommend?

**Comment by samreid** [comment]
@pixelzoom replied:

>> This was introduced for #3, and is exercised for the bamboo demo "Multiple Plots" ...
>
> It looks like there's a bug in DemoMultiplePlots.  Wasn't `yScale` renamed `yTransform`? 
>
```js
    const chartTransform = new ChartTransform( {
      viewWidth: 600,
      viewHeight: 400,
      modelXRange: new Range( 2, 10 ),
      modelYRange: new Range( 1, 22000 ),
      yScale: new Transform1( Math.log, Math.exp, {
        domain: new Range( 0, Number.POSITIVE_INFINITY ),
        range: new Range( 0, Number.POSITIVE_INFINITY )
      } )
    } );
```

> I'm not sure what to do about the code that I pointed out in > https://github.com/phetsims/bamboo/issues/40#issuecomment-931454309.  But if this does happen, isn't this silently hiding a problem? And is the correct response really to punt on the transform and return `value`?

**Comment by pixelzoom** [comment]
To clarify... DemoMultiplePlots looks like it contains a bug that's not related to this issue. `yScale` should have been renamed `yTransform`.

**Comment by samreid** [comment]
I fixed that part, thanks!  Leaving the issue open for the main part.

**Comment by samreid** [comment]
I added assertions that the transformed points are numeric and finite, and adjusted the characteristics of the demo log plot so it doesn't try to compute Math.log(0).  I fuzzed fourier and didn't see any problems.  @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
👍🏻 closing.
