### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by samreid** [phetsims/bamboo#49]
As a preliminary step before https://github.com/phetsims/bamboo/issues/42, it seems valuable to convert bamboo to TypeScript.

**Comment by jessegreenberg** [comment]
I noticed a CT error caused by the change to UpDownArrowPlot.ts, I believe it is fixed in the above commit. I also renamed `DEFAULT_PAINTABLE_OPTIONS` so that it is not as easily confused with `PAINTABLE_DEFAULT_OPTIONS`.

**Comment by samreid** [comment]
Bamboo is in TypeScript, additional improvements can be done on-demand.  Closing.
