### ISSUE TITLE
The y=mx+b sliders are oriented backwards

### ISSUE THREAD

**Issue by samreid** [phetsims/bamboo#50]
The sliders look like this, but drag up and down:

![image](https://user-images.githubusercontent.com/679486/146695401-b84f3c30-145e-40aa-b976-60c1ea93bb37.png)

Discovered in https://github.com/phetsims/bamboo/issues/49

**Comment by samreid** [comment]
I switched to use HSlider and will open a separate issue about this newly discovered VSlider problem.  It looks like this now:

![image](https://user-images.githubusercontent.com/679486/148631521-15646615-4944-44cb-aa1b-845591fdb3bf.png)

@pixelzoom is this what was intended? Or did you want vertical sliders?

**Comment by pixelzoom** [comment]
phetsims/sun#733 is fixed, so I reverted to VSlider for DemoLinearEquationPlot.

Back to @samreid for review.

**Comment by samreid** [comment]
Looks great, thanks, closing.
