### ISSUE TITLE
Export type options throughout the library

### ISSUE THREAD

**Issue by veillette** [phetsims/bamboo#54]
Most of the  (all?) classes in the bamboo library do not export their type options.

For instance, in TickLabelSet we have, 
````
type SelfOptions = {

  value?: number;
  edge?: null | 'min' | 'max'; // 'min' or 'max' put the ticks on that edge of the chart (takes precedence over value)
  origin?: number;

  // act as if there is a corresponding tick with this extent, for positioning the label relatively
  extent?: number;

  // determines whether the rounding is lenient, see ChartTransform
  clippingType?: ClippingType;

  // or return null if no label for that value
  createLabel?: ( value: number ) => Node | null;
  positionLabel?: ( label: Node, tickBounds: Bounds2, axisOrientation: Orientation ) => Node;

};
type TickLabelSetOptions = SelfOptions & PathOptions;

class TickLabelSet extends Path 

````

I'm not sure if this is an oversight or a conscious decision.
Since this is a common-code library, I would have thought that it would be nice to able to export the options that can be used for type context.

**Comment by veillette** [comment]
Assigning to @samreid  since he seems to have done the bulk of the work on this library.

**Comment by samreid** [comment]
This was an oversight, thanks!  I tried to address it in the commit.  Please review.

**Comment by veillette** [comment]
Thanks @samreid .
All the options types have been exported  in Bamboo. Closing.
