### ISSUE TITLE
Optimize memory allocation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#61]
In https://github.com/phetsims/calculus-grapher/issues/210, we are optimizing Calculus Grapher to improve responsiveness when manipulating (dragging) interactive curves. One of the challenges is reducing garbage collection (GC,) so that dragging feels smooth and is not interrupted.

We noticed that bamboo does not appear to have been optimized, and is in fact doing unnecessary memory allocation.

For example, let's look at LinePlots.ts, whose `update` methods is similar to other bamboo plots.  Making the change shown below would result in 1 less Vector2 allocation _for every member of `this.dataSet`_.  Since dataSets are typically large and often updated frequently, this is a significant optimization.

```diff
public update(): void {
  ...
      if ( dataPoint ) {
-       const viewPoint = this.chartTransform.modelToViewPosition( dataPoint );
+       const viewX = this.chartTransform.modelToViewX( dataPoint.x );
+       const viewY = this.chartTransform.modelToViewY( dataPoint.y );
        if ( moveToNextPoint ) {
-         shape.moveToPoint( viewPoint );
+         shape.moveTo( viewX, viewY );
          moveToNextPoint = false;
        }
        else {
-         shape.lineTo( viewX, viewY );
+         shape.lineToPoint( viewPoint );
        }
      }
```

**Comment by veillette** [comment]
In `KITE/Shape`, all the syntactic sugar methods associated with line and move are funneled to `lineToPoint` and `moveToPoint`. So the problems may not lies in Bamboo but in `Shape`. Otherwise, there is no way to avoid allocating a new Vector2 in Bamboo.

**Comment by pixelzoom** [comment]
@jonathanolson can you please comment on whether we can optmize Shape so that it's not allocating Vector2 for every lineTo and moveTo operation.  It seems backwards that (for example) `lineTo` allocates a Vector2 and calls `lineToPoint`.

**Comment by veillette** [comment]
This might be a huge lift:
```js
lineToPoint( point ) {
    // see http://www.w3.org/TR/2dcontext/#dom-context-2d-lineto
    if ( this.hasSubpaths() ) {
      const start = this.getLastSubpath().getLastPoint();
      const end = point;
      const line = new Line( start, end );
      this.getLastSubpath().addPoint( end );
      this.addSegmentAndBounds( line );
    }
```

`Line` extends `Segment` which makes extensive use of vector methods to find a tangent to a line.

**Comment by pixelzoom** [comment]
Ugh. I see zero optimizations that we can make in LinePlot, because of the way Shape methods are implemented.

**Comment by jonathanolson** [comment]
I'm a bit confused, perhaps this it worth a zoom call? Calling `lineToPoint()` shouldn't be allocating extra Vector2s.

**Comment by jonathanolson** [comment]
I could look into pooling the vectors that are created, however it would require tracking for Shape to know the owner of each Vector2 (since they could be directly provided by the user).

**Comment by jonathanolson** [comment]
So presumably you could pool Vector2s and use lineToPoint, and when you free them they could then be used for future allocations.

**Comment by veillette** [comment]
> I'm a bit confused, perhaps this it worth a zoom call? Calling lineToPoint() shouldn't be allocating extra Vector2s.
@pixelzoom and I were trying to save a vector allocation from Bamboo, and we naively thought that we would save one by using `lineTo( x, y )` but then Shape would create a vector allocation to pass it to `lineToPoint`. The alternative is to create a vector allocation in bamboo and then called `lineToPoint`. Either way, that six of one, half a dozen of the other.

I think your comment about pooling Vector2s in bamboo might be the way forward.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> I'm a bit confused, perhaps this it worth a zoom call? Calling lineToPoint() shouldn't be allocating extra Vector2s.

I didn't say that `lineToPoint( point )` allocates Vectors. I said that `lineTo( x, y )` allocates a Vector, and then calls `lineToPoint( point )`.  This is the opposite of an optimized implementation.  And optimized implementation would provide `lineTo( x, y )` as the more efficient method with `lineToPoint( point )` as a convenience that calls `lineTo( x, y )`.  See for example the many ModelViewTransform methods.

So is it possible to change this, so that `lineTo( x, y )` doesn't result in a Vector2 allocation?

**Comment by pixelzoom** [comment]
We got acceptable performance in calculus-grapher by making sim-specific optimizations. So we're not going to proceed with this issue. Closing.
