### ISSUE TITLE
Problems with bamboo options types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#62]
Problems noted with options types in bamboo:

- [x] SpanNode: SelfOptions and FlowboxOptions both include `spacing`.  The latter is likely unnecessary.

- [x] SpanNode exposes several options that should not be provided by the caller, according to assertions i nteh constructor.  These include 'children', 'orientation', and 'arrowNodeOptions.stroke'.  These options should be omitted from types, so that we get a TS error instead of a runtime failure.

- [x] TickLabelSetOptions should not include 'children', according to an assertion in the constructor.

- [x] CanvasGridLineSet: SelfOptions duplicates 3 fields from PathOptions.  This should be done via composition using `PickOptional` or `WithOptional`.  A 4th option `stroke` is identified as "Path options", but it's type is actually different and has nothing to do with Path.

```ts
type SelfOptions = {
  origin?: number;
  clippingType?: ClippingType;

  // Path options
  stroke?: string | CanvasGradient | CanvasPattern;
  lineDash?: number[];
  lineWidth?: number;
  lineDashOffset?: number;
};
```

I'll take a stab at fixing these, then assign to @samreid to review -- looks like he did the TypeScript conversions.

**Comment by pixelzoom** [comment]
Another problem:

* SpanNode exposes several options that should not be provided by the caller, according to assertions i nteh constructor.  These include 'children', 'orientation', and 'arrowNodeOptions.stroke'.  These options should be omitted from types, so that we get a TS error instead of a runtime failure.

**Comment by pixelzoom** [comment]
@samreid please review, close if OK.  Note that SpanNode and CanvasGridLineSet are used in CCKCChartNode.ts.

**Comment by samreid** [comment]
I reviewed the commits, it seems the checkboxes https://github.com/phetsims/bamboo/issues/62#issuecomment-1435025175 were addressed, so I checked them off.  I also tested in CCK AC.  Everything seems reasonable, thanks!  Closing.
