### ISSUE TITLE
Memory leak in TickLabelSet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#64]
Discovered in https://github.com/phetsims/fourier-making-waves/issues/259.

TickLabelSet has a `createLabel` option, which is exercised in `update`, which is called when the ChartTransform changes, or when spacing is called via`setSpacing`.

Since TickLabelSet is creating the labels, it is also responsible for their disposal -- which it is currently not doing.   If those labels happen require disposal -- for example Text/RichText that is linked to LocalizedStringProperty, as in https://github.com/phetsims/fourier-making-waves/issues/259 -- then a memory leak will occur.

**Comment by pixelzoom** [comment]
> But what if calling createLabel involves other factors, for example if it is dependent on the spacing or chart transform?

For example, in FMW DiscreteHarmonicsChartNode:

```ts
      xTickLabelSetOptions: {
        createLabel: value =>
          TickLabelUtils.createTickLabelForDomain( value, X_TICK_LABEL_DECIMALS, harmonicsChart.xAxisTickLabelFormatProperty.value,
            harmonicsChart.domainProperty.value, harmonicsChart.fourierSeries.L, harmonicsChart.fourierSeries.T )
      },
```

The labels are specific to the selected domain. If 2 domains happen to have the same value for a tick mark, then a stale label will be reused by TickLabelSet.

**Comment by pixelzoom** [comment]
TickLabelSet implements a form of caching, where it reuses labels.  Labels that are not reused are removed from the cache, but are not currently disposed, resulting in a potential leak.  Here's the relevant code:

```ts
    // empty cache of unused values
    const toRemove = [];
    for ( const key of this.labelMap.keys() ) {
      if ( !used.has( key ) ) {
        toRemove.push( key );
      }
    }
    toRemove.forEach( t => {
      this.labelMap.delete( t );
    } );
```

**Comment by pixelzoom** [comment]
Fixed in https://github.com/phetsims/bamboo/commit/44f6124187fdc3e0ab9f71a4730ef557776032b8.

@samreid and I looked at this together, and it seems safe.  So I'll consider this reviewed, and close the issue.

**Comment by pixelzoom** [comment]
Reopening. In https://github.com/phetsims/bamboo/issues/65#issuecomment-2521263684, @samreid noted:

> 2. The method `invalidateTickLabelSet` clears the labelMap without disposing of the values.

... and FWM is indeed using `invalidateTickLabelSet`, so leaking memory there.

**Comment by pixelzoom** [comment]
@samreid would you please review? Would be nice if this were done before I create the release branch for https://github.com/phetsims/fourier-making-waves/issues/247, which will probably happen Monday 12/9.

https://github.com/phetsims/bamboo/commit/2d55d7b290ae1dbc7bc9640aea1112e110835629 and https://github.com/phetsims/bamboo/commit/beff3cf5f509d1aa7ec28b6317c49f10ea44905d fix memory leaks in `invalidateTickLabelSet` and `dispose` respectively, by disposing of cached labels.

https://github.com/phetsims/bamboo/commit/7527ae2927ed217549858480e6e4f80c3e616909 improved the readability of the piece of code that gets a cached label or creates a new one.  Nested ternary operators made this difficult to read.

https://github.com/phetsims/bamboo/commit/95f208bdc242b40c783b35463394f6ae50812aac (and a bit that got committed accidentally in https://github.com/phetsims/bamboo/commit/7527ae2927ed217549858480e6e4f80c3e616909) simplifies the implementation of removing unused labels -- fewer loops (1 vs 2), and no need for a `Set`.

**Comment by samreid** [comment]
Looks good, and I tested at runtime in the bamboo harness to make sure disposal worked as expected. Anything else before closing?

**Comment by pixelzoom** [comment]
Thanks for the speedy review. Nothing else to do here. Closing.
