### ISSUE TITLE
missing features in TickMarkSet 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#8]
TickMarkSet current lacks the ability to change spacing, which is part of the API for GridLineSet and LabelSet (see `setSpacing`).    It also doesn't implement `dispose`, and will leak a listener attached to `chartModel`.

I need this functionality in Fourier, where grid/ticks/labels change based on zoom level.   So I took a stab at correcting this -- add a `setSpacing` method, factor out `updateTickMarkSet`, etc.    I immediately ran into something I don't understand in the `chartModel` listener:

```js
     const used = new Set();
...
        used.add( modelPosition );
```

I can't tell what `used` is doing here - probably nothing? Maybe this is part of a copy-paste from LabelSet, where `used` does play a role in managing a cache? Does TickMarkSet need a similar cache?

**Comment by samreid** [comment]
LabelSet needs a cache to avoid recreating label nodes, it is not necessary for TickMarkSet, and I removed it in the commit.  Next I'll look at adding `setSpacing`.

**Comment by samreid** [comment]
I added TickMarkSet.setSpacing and tested with this code in DemoHarmonicsChart:

```js
    const tickMarkSet = new TickMarkSet( chartModel, Orientation.VERTICAL, 0.5, { edge: 'min' } );

    const t = Date.now();
    setInterval( () => {
      const t2 = Date.now();
      const dt = t2 - t;
      tickMarkSet.setSpacing( 0.5 * Math.abs( Math.sin( dt / 1000 ) ) );
    }, 18 );
```

I also added dispose.  @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
Looks good, and tested in Fourier. Closing.
