### ISSUE TITLE
How should tick marks look around the edges of the graph?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bamboo#9]
When tick marks are added around the edge of the graph (option `edge: 'min'` or `edge: 'max'`), should they extend into the interior of the graph, like bamboo currently does?  Example from Fourier:

<img width="184" alt="screenshot_704" src="https://user-images.githubusercontent.com/3046552/100686286-3d550080-333b-11eb-8018-a53eea0d0b0b.png">

Or should the be fully outside the graph? Example from Natural Selection:

<img width="125" alt="screenshot_705" src="https://user-images.githubusercontent.com/3046552/100686295-4219b480-333b-11eb-8581-effa2df070dd.png">

Or do we need to support both?  

My preference is the look from Natural Selection, where they do not extend into the interior of the graph, and therefore cannot interfere with what is being plotted (lines, points, etc).  We can of course support both, but that's more options, more complicated code, and questionable whether it's necessary.

@arouinfar your thoughts?   @samreid FYI.

**Comment by samreid** [comment]
We can use the z-ordering to achieve this look without introducing more options or more complicated code.  For instance, moving 2 lines of code in DemoHarmonicsChart it can look like this:

![image](https://user-images.githubusercontent.com/679486/100694902-45b63700-334d-11eb-9b0d-8ede7500a724.png)

<details>

```diff

Index: js/demo/DemoHarmonicsChart.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/demo/DemoHarmonicsChart.js	(revision 7989d8477f796d19a290f6ab4a53257f7205f061)
+++ js/demo/DemoHarmonicsChart.js	(date 1606794369075)
@@ -63,6 +63,9 @@
     // Anything you want clipped goes in here
     this.children = [
 
+      new TickMarkSet( chartModel, Orientation.VERTICAL, 0.5, { edge: 'min' } ),
+      new LabelSet( chartModel, Orientation.VERTICAL, 0.5, { edge: 'min' } ),
+
       // Background
       chartRectangle,
 
@@ -88,8 +91,7 @@
       } ),
 
       // Tick marks outside the chart
-      new TickMarkSet( chartModel, Orientation.VERTICAL, 0.5, { edge: 'min' } ),
-      new LabelSet( chartModel, Orientation.VERTICAL, 0.5, { edge: 'min' } ),
+
       new TickMarkSet( chartModel, Orientation.HORIZONTAL, Math.PI / 8, { edge: 'min' } ),
       new LabelSet( chartModel, Orientation.HORIZONTAL, Math.PI / 8, {
         edge: 'min',

```

</details>

**Comment by pixelzoom** [comment]
👍🏻 closing.
